-- Project Desk: paste into Supabase SQL Editor and run once.
-- Set this email to the same value as WORKSPACE_OWNER_EMAIL in Vercel.
create table if not exists public.ba_workspace_config (
  singleton boolean primary key default true check (singleton),
  owner_email text not null
);
alter table public.ba_workspace_config enable row level security;
insert into public.ba_workspace_config(singleton,owner_email)
values (true,'priyanknegi41@gmail.com') on conflict(singleton) do nothing;

create or replace function public.ba_is_workspace_owner()
returns boolean language sql stable security definer set search_path=public
as $$ select exists(select 1 from ba_workspace_config where singleton and lower(owner_email)=lower(auth.jwt()->>'email')); $$;
revoke all on function public.ba_is_workspace_owner() from public;
grant execute on function public.ba_is_workspace_owner() to authenticated;

create table if not exists public.ba_workspace_records (
  id bigint generated by default as identity primary key,
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  kind text not null,
  project text not null default '',
  data jsonb not null,
  created timestamptz not null default now(),
  updated timestamptz not null default now(),
  request_id uuid,
  unique(owner_id,request_id)
);
create index if not exists ba_workspace_records_owner_kind_project
on public.ba_workspace_records(owner_id,kind,project);
alter table public.ba_workspace_records enable row level security;
drop policy if exists ba_records_owner on public.ba_workspace_records;
create policy ba_records_owner on public.ba_workspace_records for all to authenticated
using(owner_id=auth.uid() and public.ba_is_workspace_owner())
with check(owner_id=auth.uid() and public.ba_is_workspace_owner());
grant select,insert,update,delete on public.ba_workspace_records to authenticated;
grant usage,select on sequence public.ba_workspace_records_id_seq to authenticated;

-- Save records and their activity entries in one transaction.
create or replace function public.ba_save_records(items jsonb)
returns jsonb language plpgsql security invoker set search_path=public
as $$
declare item jsonb; payload jsonb; record_id bigint; record_kind text;
project_id text; operation_id uuid; result jsonb='[]'::jsonb; now_at timestamptz=now();
linked_id text; person text;
begin
 if auth.uid() is null or not public.ba_is_workspace_owner() then raise exception 'BA: Sign in as the workspace owner.' using errcode='42501'; end if;
 if jsonb_typeof(items)!='array' or jsonb_array_length(items)<1 or jsonb_array_length(items)>100 then raise exception 'BA: Invalid record batch.'; end if;
 for item in select value from jsonb_array_elements(items) loop
  payload=item->'data';record_kind=item->>'kind';project_id=coalesce(item->>'project','');
  if not record_kind=any(array['projects','requirements','stories','tasks','issues','changes','milestones','notes','proposals']) then raise exception 'BA: Invalid record type.'; end if;
  if jsonb_typeof(payload)!='object' or length(trim(coalesce(payload->>'title','')))=0 then raise exception 'BA: A title is required.'; end if;
  if length(payload::text)>100000 then raise exception 'BA: Content is too long.'; end if;
  if project_id!='' and not exists(select 1 from ba_workspace_records where id::text=project_id and kind='projects' and owner_id=auth.uid()) then raise exception 'BA: Choose an existing project.'; end if;
  if record_kind not in ('projects','proposals') and project_id='' then raise exception 'BA: Select a project.'; end if;
  if coalesce(item->>'id','')!='' then
   update ba_workspace_records set data=payload,project=project_id,updated=now_at
   where id=(item->>'id')::bigint and kind=record_kind and owner_id=auth.uid() returning id into record_id;
   if record_id is null then raise exception 'BA: This record no longer exists.'; end if;
  else
   operation_id=nullif(payload->>'submissionId','')::uuid;
   insert into ba_workspace_records(kind,project,data,created,updated,request_id)
   values(record_kind,project_id,payload,now_at,now_at,operation_id)
   on conflict(owner_id,request_id) do nothing returning id into record_id;
   if record_id is null then
    select id into record_id from ba_workspace_records where owner_id=auth.uid() and request_id=operation_id;
    result=result||to_jsonb(record_id);continue;
   end if;
  end if;
  person=coalesce(auth.jwt()->>'email','Workspace owner');
  insert into ba_workspace_records(kind,project,data,created,updated)
  values('activity',case when record_kind='projects' then record_id::text else project_id end,
   jsonb_build_object('title',(payload->>'title')||case when coalesce(item->>'id','')='' then ' · created' else ' · updated' end,'person',person,'status',coalesce(payload->>'status','Draft'),'recordKind',record_kind),now_at,now_at);
  result=result||to_jsonb(record_id);
 end loop;
 return result;
end $$;
revoke all on function public.ba_save_records(jsonb) from public;
grant execute on function public.ba_save_records(jsonb) to authenticated;

-- Restore the ZIP's existing-data backup into an empty workspace only.
create or replace function public.ba_import_workspace(records jsonb)
returns integer language plpgsql security definer set search_path=public
as $$
declare row_data jsonb; imported integer=0; max_id bigint;
begin
 if auth.uid() is null or not public.ba_is_workspace_owner() then raise exception 'BA: Sign in as the workspace owner.' using errcode='42501'; end if;
 if exists(select 1 from ba_workspace_records where owner_id=auth.uid()) then raise exception 'BA: Import requires an empty workspace. Existing data was not changed.'; end if;
 if jsonb_typeof(records)!='array' or jsonb_array_length(records)>10000 then raise exception 'BA: Invalid backup.'; end if;
 for row_data in select value from jsonb_array_elements(records) loop
  if not (row_data->>'kind')=any(array['projects','requirements','stories','tasks','issues','changes','milestones','notes','proposals','activity']) then raise exception 'BA: Invalid backup record type.'; end if;
  if jsonb_typeof(row_data->'id')!='number' then raise exception 'BA: Invalid backup record ID.'; end if;
  insert into ba_workspace_records(id,kind,project,data,created,updated)
  values((row_data->>'id')::bigint,row_data->>'kind',coalesce(row_data->>'project',''),row_data-array['id','kind','project','created','updated'],coalesce((row_data->>'created')::timestamptz,now()),coalesce((row_data->>'updated')::timestamptz,now()));
  imported=imported+1;
 end loop;
 select max(id) into max_id from ba_workspace_records;
 if max_id is not null then perform setval('ba_workspace_records_id_seq',max_id,true); end if;
 return imported;
end $$;
revoke all on function public.ba_import_workspace(jsonb) from public;
grant execute on function public.ba_import_workspace(jsonb) to authenticated;
