 'use client';
import {useEffect,useState} from 'react';
import {apiRequest} from '@/lib/api-client';
import {defaults,Preferences,detect} from '@/lib/notification-rules';
import {Row} from '@/lib/model';
import {toast} from 'sonner';
export function NotificationSettings({rows,onOpen,center=false,demo=false}:{rows:Row[];onOpen:(r:Row)=>void;center?:boolean;demo?:boolean}){
 const [prefs,setPrefs]=useState<Preferences>(defaults),[info,setInfo]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){if(demo){setInfo({configured:false,schedule:'Daily around 09:00 IST',logs:[]});return}try{const data=await apiRequest('/api/notifications');setInfo(data);setPrefs(data.preferences);setError('')}catch(e){setError((e as Error).message)}}useEffect(()=>{load()},[demo]);
 async function action(body:any){if(demo){toast.info('Preview only. No preferences saved or emails sent.');return}setBusy(true);try{await apiRequest('/api/notifications',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});toast.success(body.action==='test'?'Test email accepted by provider':body.action==='read'?'Notifications marked read':'Preferences saved');await load()}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
 const labels:Record<string,string>={email_enabled:'Enable email notifications',daily_digest_enabled:'Daily summary email',task_due:'Tasks due soon',task_overdue:'Overdue tasks',project_overdue:'Project timeline overdue',milestone_due:'Upcoming milestones',milestone_overdue:'Overdue milestones',blocked:'Blocked task follow-ups',pending:'Pending approvals',critical:'Critical unresolved issues'};
 if(center)return <><section className="panel"><div className="panel-title"><h2>Needs your attention</h2><button onClick={()=>action({action:'read'})} disabled={busy||!info}>Mark all read</button></div>{detect(rows,{...prefs,task_due:true,task_overdue:true,project_overdue:true,milestone_due:true,milestone_overdue:true,blocked:true,pending:true,critical:true}).map(e=><button className="notification-record" key={e.key} onClick={()=>onOpen(e.record)}><strong>{e.record.title}</strong><span>{e.reason} · {e.record.status}</span><small>Open record →</small></button>)}{!detect(rows,prefs).length&&<p className="empty-text">Everything is currently on track.</p>}</section><History info={info} error={error} rows={rows} onOpen={onOpen}/></>;
 return <><div className="settings-grid"><section className="panel settings-form"><h2>Email reminders</h2><p>Keep due dates, approvals and delivery delays visible.</p>{error&&<p className="auth-error">{error}</p>}{Object.entries(labels).map(([key,label])=><label className="setting-toggle" key={key}><span>{label}</span><input type="checkbox" checked={!!(prefs as any)[key]} onChange={e=>setPrefs({...prefs,[key]:e.target.checked})}/></label>)}<label>Recipient email<input type="email" value={prefs.recipient_email} onChange={e=>setPrefs({...prefs,recipient_email:e.target.value})}/></label><div className="form-grid"><label>Remind before deadline<select value={prefs.due_soon_days} onChange={e=>setPrefs({...prefs,due_soon_days:Number(e.target.value)})}>{[1,2,3,7].map(v=><option key={v} value={v}>{v} day(s)</option>)}</select></label><label>Pending / blocked threshold<select value={prefs.pending_days} onChange={e=>setPrefs({...prefs,pending_days:Number(e.target.value)})}>{[1,2,3,7].map(v=><option key={v} value={v}>{v} day(s)</option>)}</select></label></div><label>Timezone<input value={prefs.timezone} onChange={e=>setPrefs({...prefs,timezone:e.target.value})}/></label><div className="settings-actions"><button className="primary" disabled={busy||!info} onClick={()=>action({preferences:prefs})}>Save preferences</button><button className="secondary" disabled={busy||!info?.configured} onClick={()=>action({action:'test'})}>Send test email</button></div></section><section className="panel settings-form"><h2>Automation status</h2><dl><dt>Email provider</dt><dd>{info?.configured?'Configured':'Not configured'}</dd><dt>Sender</dt><dd>{info?.sender||'Set sender in Vercel'}</dd><dt>Last scheduled check</dt><dd>{info?.last_check?new Date(info.last_check).toLocaleString():'No check recorded yet'}</dd><dt>Schedule</dt><dd>{info?.schedule||'Daily around 09:00 IST'}</dd></dl><p>The website can be closed. Reminders run on the server after deployment and setup.</p><p>Due reminders are sent once per deadline. Remaining overdue items appear in the daily summary. Sample records are excluded.</p><p>Sender-domain verification must be completed in Resend. Provider acceptance does not guarantee inbox delivery.</p></section></div><History info={info} error={error} rows={rows} onOpen={onOpen}/></>;
}
function History({info,error,rows,onOpen}:{info:any;error:string;rows:Row[];onOpen:(r:Row)=>void}){return <section className="panel activity-wrap"><div className="panel-title"><h2>Notification & email history</h2><span>Latest 100 events</span></div>{error&&<p className="empty-text">{error}</p>}<div className="table-scroll"><table className="notification-history"><thead><tr><th>Date</th><th>Subject</th><th>Recipient</th><th>Status</th></tr></thead><tbody>{info?.logs?.map((log:any)=><tr key={log.id}><td>{new Date(log.created_at).toLocaleString()}</td><td><button onClick={()=>{const r=rows.find(r=>r.id===log.record_id);if(r)onOpen(r)}}>{!log.read_at?'● ':''}{log.subject}</button>{log.error_message&&<small className="late">{log.error_message}</small>}</td><td>{log.recipient||'In-app only'}</td><td>{log.status==='sent'?'Accepted by provider':log.status}</td></tr>)}</tbody></table></div>{!info?.logs?.length&&<p className="empty-text">No notification deliveries yet.</p>}</section>}
