export type Row = {id:number;kind:string;project:string;created:string;updated:string;[key:string]:any};
export type Field={key:string;label:string;type?:string;options?:string[]};
const f=(key:string,label:string,type='text',options?:string[]):Field=>({key,label,type,options});
const priority=f('priority','Priority','select',['Low','Medium','High','Critical']);
const dev=f('developer','Assigned developer'); const moduleField=f('module','Module'); const requirement=f('requirement','Linked requirement','requirements');const story=f('story','Linked user story','stories');const notes=f('internalNotes','Internal notes','textarea');const approval=f('approval','Client approval','select',['Pending','Approved','Rejected']);
export const statuses:Record<string,string[]>={projects:['Planning','Active','On Hold','Testing','Client Review','Completed','Delayed'],requirements:['Draft','Pending Clarification','Approved','In Development','Testing','Completed','Rejected'],stories:['Draft','Approved','In Development','Testing','Completed'],tasks:['Backlog','Pending','To Do','In Progress','Testing','Blocked','Completed'],issues:['Open','Discussion Required','Action Required','Resolved'],changes:['Received','Under Discussion','Approved','In Development','Completed','Rejected'],milestones:['Not Started','In Progress','Completed','Delayed'],notes:['Recorded','Action Required','Closed'],proposals:['Draft','Ready','Sent']};
const status=(kind:string)=>f('status','Status','select',statuses[kind]);
export const names:Record<string,string>={projects:'Projects',requirements:'Requirements',stories:'User Stories',tasks:'Tasks',issues:'Issues & Discussions',changes:'Changes',milestones:'Timeline',notes:'Notes',proposals:'Proposals'};
export const prefixes:Record<string,string>={projects:'PRJ',requirements:'REQ',stories:'US',tasks:'TASK',issues:'ISS',changes:'CR',milestones:'MS',notes:'NOTE',proposals:'PROP'};
export const code=(r:Row)=>`${prefixes[r.kind]??'ACT'}-${String(r.id).padStart(3,'0')}`;
export const fields:Record<string,Field[]>={
projects:[f('title','Project name'),f('client','Client name'),f('company','Client company'),f('clientEmail','Client email','email'),f('clientPhone','Client phone'),f('type','Project type','select',['Website','Mobile Application','ERP','CRM','E-commerce','Delivery Platform','Custom Software','Other']),f('description','Project description','textarea'),f('start','Start date','date'),f('delivery','Original expected delivery','date'),f('revised','Current expected delivery','date'),f('phase','Current phase','select',['Requirement Gathering','UI/UX','Development','Testing','UAT','Deployment','Live']),f('progress','Progress (%)','number'),status('projects'),priority,dev,f('coordinator','Business analyst / coordinator'),f('value','Project value (₹, optional)','number'),notes],
requirements:[f('title','Requirement title'),f('description','Detailed requirement','textarea'),moduleField,f('type','Requirement type','select',['Functional','Non-Functional','Business Rule','Integration','UI/UX','Reporting']),priority,f('requestedBy','Requested by'),f('requestedDate','Requested date','date'),status('requirements'),approval,f('clarification','Client clarification required','boolean'),f('question','Pending client question','textarea'),dev,story,notes],
stories:[f('title','Story title'),f('role','As a'),f('want','I want','textarea'),f('purpose','So that / business purpose','textarea'),f('criteria','Acceptance criteria (one per line)','textarea'),priority,status('stories'),requirement,dev,moduleField],
tasks:[f('title','Task title'),f('description','Detailed description','textarea'),moduleField,requirement,story,dev,f('assigned','Assigned date','date'),f('due','Due date','date'),priority,status('tasks'),f('update','Developer update','textarea'),f('blocked','Blocked','boolean'),f('blocker','Blocker reason','textarea'),f('discussionDate','Last discussion date','date'),notes],
issues:[f('title','Issue title'),moduleField,requirement,f('problem','Problem / question','textarea'),f('discussedWith','Discussed with'),f('discussionDate','Discussion date','date'),f('response','Developer response','textarea'),f('decision','Final decision','textarea'),f('action','Action required','textarea'),dev,f('due','Due date','date'),status('issues'),notes],
changes:[f('title','Change title'),f('original','Original scope / requirement','textarea'),f('requestedChange','Requested change','textarea'),f('requestedBy','Requested by'),f('requestedDate','Request date','date'),f('reason','Reason for change','textarea'),moduleField,requirement,f('impact','Developer impact','textarea'),f('timelineImpact','Timeline impact (days)','number'),f('costImpact','Additional cost (₹)','number'),priority,approval,f('decision','Final decision','textarea'),dev,status('changes'),notes],
milestones:[f('title','Milestone','select',['Requirement Gathering','UI/UX','Development','Testing','UAT','Deployment']),f('plannedStart','Planned start','date'),f('plannedEnd','Planned end','date'),f('actualStart','Actual start','date'),f('actualEnd','Actual end','date'),dev,status('milestones'),f('delayReason','Delay reason','textarea'),notes],
notes:[f('title','Meeting / note title'),f('date','Date','date'),f('type','Meeting type','select',['Client Meeting','Developer Discussion','Internal Meeting','Requirement Discussion','UAT Discussion','General Note']),f('participants','Participants'),f('summary','Discussion summary','textarea'),f('decision','Important decisions','textarea'),f('newRequirements','New requirements identified','textarea'),f('actions','Action items (owner and due date)','textarea'),f('questions','Pending questions','textarea'),f('followup','Next follow-up','date'),status('notes'),notes],
proposals:[f('title','Document title','textarea'),f('projectName','Project name'),f('subtitle','Services / cover subtitle'),f('coverRecipient','Cover line / prepared for (optional)'),f('investment','Investment (optional)'),f('duration','Proposal duration (optional)'),f('coverNote','Cover footer note (optional)'),f('client','Client name (optional)'),f('company','Client company (optional)'),f('clientEmail','Client email (optional)','email'),f('clientPhone','Client phone (optional)'),f('clientAddress','Client address (optional)','textarea'),f('date','Document date','date'),f('preparedBy','Prepared by (optional)'),f('preparedCompany','Prepared-by company (optional)'),f('coverTemplate','Cover template','select',['Waplia','Project Desk']),status('proposals'),f('content','Proposal content','textarea')]
};
export const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'});
export const date=(v:string)=>v?new Date(v+'T12:00:00').toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}):'—';
export const overdue=(r:Row)=>!!r.due&&r.due<today()&&!['Completed','Resolved','Closed'].includes(r.status);
export function sampleItems(){const projects=[{title:'Food Delivery Application',client:'Urban Kitchen',type:'Delivery Platform',description:'Single restaurant ordering app with customer and delivery partner experiences. Includes scheduled orders and live delivery tracking.',phase:'Development',progress:64,status:'Active',priority:'High',developer:'Rahul Sharma, Aditi Mehta',start:'2026-09-14',delivery:'2026-10-22',revised:'2026-10-25'},{title:'Multi Vendor E-commerce',client:'CT Kart',type:'E-commerce',description:'Marketplace with seller catalogues, orders, commissions and logistics.',phase:'Testing',progress:82,status:'Testing',priority:'High',developer:'Aditi Mehta, Vikram Singh',start:'2026-08-20',delivery:'2026-10-03',revised:'2026-10-10'},{title:'Farm Management ERP',client:'Green Acre',type:'ERP',description:'Land assignment, crop operations, inventory and manager attendance.',phase:'UI/UX',progress:28,status:'Active',priority:'Medium',developer:'Neha Joshi, Rahul Sharma',start:'2026-09-28',delivery:'2026-11-02',revised:'2026-11-02'},{title:'CRM Platform',client:'Vista Realty',type:'CRM',description:'Lead capture, ownership and follow-up for a real estate sales team.',phase:'Requirement Gathering',progress:15,status:'Planning',priority:'Medium',developer:'Vikram Singh',start:'2026-10-01',delivery:'2026-11-06',revised:'2026-11-06'}];return projects.map(p=>({kind:'projects',project:'',data:{...p,coordinator:'Priyanshu Negi',sample:true}}));}
export function sampleDetails(p:Row){const food=p.type==='Delivery Platform';const module=food?'Scheduled delivery':'Core workflow';return [
{kind:'requirements',data:{title:food?'Schedule an order delivery':'Role-based access permissions',description:food?'Customers select an available date and delivery window at checkout. Store the window with the order; administrators can view it in order details.':'Users only see data assigned to their role. Confirm permissions with the client before implementation.',module,type:'Functional',priority:'High',status:'Pending Clarification',approval:'Pending',clarification:true,question:food?'Can a customer cancel within two hours of the selected window?':'Confirm which roles can export records.',developer:p.developer.split(',')[0],requestedBy:p.client,requestedDate:'2026-10-04'}},
{kind:'stories',data:{title:food?'Choose a delivery window':'View assigned records',role:food?'Customer':'Manager',want:food?'to select an available delivery window':'to view records assigned to me',purpose:food?'I can receive the order at a convenient time':'I can manage my responsibilities',criteria:'Only available options appear\nSelection is saved successfully\nAdministrator can review the selection\nA clear error appears when saving fails',status:'Draft',priority:'High',module,developer:p.developer.split(',')[0]}},
{kind:'tasks',data:{title:food?'Implement delivery slot validation':'Implement permission checks',description:'Validate all inputs on the server and add clear error responses.',module,developer:p.developer.split(',')[0],assigned:'2026-10-02',due:'2026-10-07',priority:'High',status:'In Progress',update:'Validation endpoint ready; integration in progress.'}},
{kind:'tasks',data:{title:'Confirm edge cases with client',module,developer:'Priyanshu Negi',assigned:'2026-10-01',due:'2026-10-03',priority:'High',status:'Blocked',blocked:true,blocker:'Awaiting client response.'}},
{kind:'issues',data:{title:food?'Scheduled order assignment logic unclear':'Export permissions need confirmation',module,problem:food?'When should a scheduled order be assigned to a partner with active deliveries?':'Which user roles can download reports?',discussedWith:p.developer,discussionDate:'2026-10-04',response:food?'Assign closer to the selected dispatch window.':'Limit export to administrator until approved.',decision:food?'Keep order unassigned until dispatch window begins.':'Await client approval of the role matrix.',action:'Coordinator to confirm the rule with the client.',developer:'Priyanshu Negi',due:'2026-10-06',status:'Action Required'}},
{kind:'changes',data:{title:food?'Add cash on delivery':'Add CSV export',original:food?'Online payment only.':'View records in the portal.',requestedChange:food?'Allow cash collection by the delivery partner.':'Allow administrators to export filtered records.',requestedBy:p.client,requestedDate:'2026-10-04',reason:'Client operational requirement',module,impact:'New validation and reconciliation workflow.',timelineImpact:3,costImpact:5000,priority:'Medium',approval:'Pending',status:'Under Discussion',developer:p.developer.split(',')[0]}},
...['Requirement Gathering','UI/UX','Development','Testing','UAT','Deployment'].map((title,i)=>({kind:'milestones',data:{title,plannedStart:`2026-10-${String(1+i*4).padStart(2,'0')}`,plannedEnd:`2026-10-${String(4+i*4).padStart(2,'0')}`,status:i<2?'Completed':i===2?'In Progress':'Not Started',developer:i===0?'Priyanshu Negi':p.developer.split(',')[0]}})),
{kind:'notes',data:{title:'Scope clarification call',date:'2026-10-04',type:'Client Meeting',participants:`Priyanshu Negi, ${p.client}`,summary:'Reviewed current scope and outstanding client questions.',decision:'New requests will be recorded separately from approved scope.',actions:'Priyanshu — confirm pending questions by 06 Oct.',questions:'Confirm approval for the new change request.',followup:'2026-10-06',status:'Recorded'}}
].map(r=>({...r,project:String(p.id),data:{...r.data,sample:true}}));}
