import {createClient} from '@supabase/supabase-js';
import {defaults,detect,localDay,Preferences} from './notification-rules';
import {Row} from './model';
export function adminDatabase(){if(!process.env.SUPABASE_SERVICE_ROLE_KEY||!process.env.NEXT_PUBLIC_SUPABASE_URL)throw Error('Configure SUPABASE_SERVICE_ROLE_KEY and Supabase URL on the server.');return createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}})}
const escape=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export async function sendEmail(to:string,subject:string,lines:string[],key:string,recordId?:number){
 if(!process.env.RESEND_API_KEY||!process.env.RESEND_FROM_EMAIL||!process.env.APP_URL)throw Error('Configure RESEND_API_KEY, RESEND_FROM_EMAIL and APP_URL.');
 const base=new URL(process.env.APP_URL);if(base.protocol!=='https:'&&base.hostname!=='localhost')throw Error('APP_URL must use HTTPS.');if(recordId)base.searchParams.set('record',String(recordId));
 let res:Response|undefined;for(let attempt=0;attempt<3;attempt++){try{res=await fetch('https://api.resend.com/emails',{method:'POST',signal:AbortSignal.timeout(15000),headers:{Authorization:'Bearer '+process.env.RESEND_API_KEY,'Content-Type':'application/json','Idempotency-Key':key},body:JSON.stringify({from:process.env.RESEND_FROM_EMAIL,to:[to],subject,text:['Project Desk',subject,...lines,base.href].join('\n'),html:`<div style="font-family:Arial;color:#202820;max-width:580px;margin:auto;padding:32px;border-top:5px solid #173d32"><h2>Project Desk</h2><h3>${escape(subject)}</h3>${lines.map(l=>`<p>${escape(l)}</p>`).join('')}<a href="${escape(base.href)}" style="display:inline-block;padding:12px 20px;background:#173d32;color:white;text-decoration:none">Open workspace</a><p style="color:#68746b;font-size:12px">Manage reminders in Settings → Notifications.</p></div>`})});if(res.status!==429&&res.status<500)break;if(attempt===2)break;}catch(e){if(attempt===2)throw e;}}
 if(!res)throw Error('Email provider unavailable');const body=await res.json();if(!res.ok)throw Error(body.message||'Email provider rejected the request');return body.id as string;
}
export async function processNotifications(){const db=adminDatabase();const {data:settings,error}=await db.from('ba_notification_preferences').select('*');if(error)throw error;let sent=0,failed=0;
 for(const setting of settings||[]){const owner=process.env.WORKSPACE_OWNER_EMAIL?.trim().toLowerCase();if(!owner)throw Error('Configure WORKSPACE_OWNER_EMAIL.');const account=await db.auth.admin.getUserById(setting.owner_id);if(account.error||account.data.user?.email?.toLowerCase()!==owner)continue;const prefs:Preferences={...defaults,...setting.data};const now=new Date();const {data,error}=await db.from('ba_workspace_records').select('*').eq('owner_id',setting.owner_id);if(error)throw error;const rows:Row[]=(data||[]).map(r=>({...r.data,id:r.id,kind:r.kind,project:r.project,created:r.created,updated:r.updated}));const events=detect(rows,prefs,now);
 const recipient=prefs.email_enabled?prefs.recipient_email:'';if(prefs.email_enabled&&!recipient)continue;
 const jobs=events.map(e=>({key:e.key,subject:`${e.type.replaceAll('_',' ')}: ${e.record.title}`,id:e.record.id,lines:[e.reason,'Project: '+(rows.find(p=>String(p.id)===e.record.project)?.title||e.record.title),'Owner: '+(e.record.developer||'Unassigned'),'Status: '+e.record.status]}));
 if(prefs.email_enabled&&prefs.daily_digest_enabled&&events.length)jobs.push({key:'digest:'+localDay(now,prefs.timezone),subject:'Project Desk — Daily Brief',id:0,lines:events.map(e=>`${e.record.title}: ${e.reason}`)});
 for(const job of jobs){const {data:log,error:insertError}=await db.from('ba_notification_logs').insert({owner_id:setting.owner_id,event_key:job.key,recipient,subject:job.subject,record_id:job.id||null,status:recipient?'queued':'internal'}).select('id').single();if(insertError){if(insertError.code==='23505')continue;throw insertError}if(!recipient)continue;
 try{const id=await sendEmail(recipient,job.subject,job.lines,'pd-'+log.id,job.id);const {error:updateError}=await db.from('ba_notification_logs').update({status:'sent',sent_at:new Date().toISOString(),provider_message_id:id}).eq('id',log.id);if(updateError)throw updateError;sent++}catch(e){await db.from('ba_notification_logs').update({status:'failed',error_message:(e as Error).message}).eq('id',log.id);failed++}}
 const {error:updateError}=await db.from('ba_notification_preferences').update({last_check:now.toISOString()}).eq('owner_id',setting.owner_id);if(updateError)throw updateError;
 }return {sent,failed};}
