import {userDatabase,AuthError} from '@/lib/auth/server';
import {defaults} from '@/lib/notification-rules';
import {adminDatabase,sendEmail} from '@/lib/notification-server';
export const dynamic='force-dynamic';
function failure(e:unknown){return Response.json({error:e instanceof AuthError?e.message:(e as Error).message},{status:e instanceof AuthError?e.status:503})}
export async function GET(request:Request){try{const {supabase,user}=await userDatabase(request);const [prefs,logs]=await Promise.all([supabase.from('ba_notification_preferences').select('*').eq('owner_id',user.id).maybeSingle(),supabase.from('ba_notification_logs').select('*').eq('owner_id',user.id).order('created_at',{ascending:false}).limit(100)]);if(prefs.error||logs.error)throw Error('Run supabase/notifications.sql in Supabase first.');return Response.json({preferences:{...defaults,...prefs.data?.data},last_check:prefs.data?.last_check,logs:logs.data,configured:!!(process.env.RESEND_API_KEY&&process.env.RESEND_FROM_EMAIL&&process.env.SUPABASE_SERVICE_ROLE_KEY&&process.env.APP_URL&&process.env.CRON_SECRET),sender:process.env.RESEND_FROM_EMAIL||'',schedule:'Daily around 09:00 IST; delivery time is approximate.'})}catch(e){return failure(e)}}
export async function POST(request:Request){try{const {supabase,user}=await userDatabase(request);const body=await request.json();
 if(body.action==='read'){const db=adminDatabase();const {error}=await db.from('ba_notification_logs').update({read_at:new Date().toISOString()}).eq('owner_id',user.id).is('read_at',null);if(error)throw error;return Response.json({ok:true})}
 if(body.action==='test'){const {data,error}=await supabase.from('ba_notification_preferences').select('data').eq('owner_id',user.id).single();if(error||!data?.data?.recipient_email)throw Error('Save a recipient email first.');const db=adminDatabase();const {data:recent,error:recentError}=await db.from('ba_notification_logs').select('id').eq('owner_id',user.id).eq('subject','Project Desk test email').gte('created_at',new Date(Date.now()-60000).toISOString());if(recentError)throw recentError;if(recent?.length)return Response.json({error:'Please wait one minute before testing again.'},{status:429});const {data:log,error:logError}=await db.from('ba_notification_logs').insert({owner_id:user.id,event_key:'test:'+crypto.randomUUID(),recipient:data.data.recipient_email,subject:'Project Desk test email',status:'queued'}).select('id').single();if(logError)throw logError;try{const id=await sendEmail(data.data.recipient_email,'Project Desk test email',['Email notifications are configured correctly.'],'pd-'+log.id);await db.from('ba_notification_logs').update({status:'sent',provider_message_id:id,sent_at:new Date().toISOString()}).eq('id',log.id);return Response.json({ok:true})}catch(e){await db.from('ba_notification_logs').update({status:'failed',error_message:(e as Error).message}).eq('id',log.id);throw e}}
 const input=body.preferences||{};const prefs={...defaults};for(const key of Object.keys(defaults))if(key in input)(prefs as any)[key]=input[key];
 for(const [key,value] of Object.entries(defaults))if(typeof value==='boolean'&&typeof (prefs as any)[key]!=='boolean')throw Error('Invalid notification toggle.');
 if(typeof prefs.recipient_email!=='string'||(prefs.recipient_email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(prefs.recipient_email))||prefs.recipient_email.length>254)throw Error('Enter a valid recipient email.');if(prefs.email_enabled&&!prefs.recipient_email)throw Error('Recipient email is required.');
 if(![1,2,3,7].includes(Number(prefs.due_soon_days))||![1,2,3,7].includes(Number(prefs.pending_days)))throw Error('Invalid reminder threshold.');try{new Intl.DateTimeFormat('en',{timeZone:prefs.timezone})}catch{throw Error('Invalid timezone.');}
 const {error}=await supabase.from('ba_notification_preferences').upsert({owner_id:user.id,data:prefs});if(error)throw Error('Save failed. Run the notification migration first.');return Response.json({ok:true})}catch(e){return failure(e)}}
